name: dart_shelf_firebase_example
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  collection: ^1.17.0
  googleapis: ^9.2.0
  googleapis_auth: ^1.3.1
  http: ^0.13.5
  shelf: ^1.3.2
  shelf_router: ^1.1.3
  shelf_router_generator: ^1.0.3

dev_dependencies:
  build_runner: ^2.3.2
  lints: ^2.0.0
  test: ^1.16.0
